SESSION_TYPE_MEETING = 1
SESSION_TYPE_PLANNING = 2
SESSION_TYPE_BREAK = 3
SESSION_TYPE_PRESENTATION = 4

SESSION_TYPES = (
    (SESSION_TYPE_MEETING, 'Meeting'),
    (SESSION_TYPE_PLANNING, 'Planning'),
    (SESSION_TYPE_BREAK, 'Break'),
    (SESSION_TYPE_PRESENTATION, 'Presentation/Talking'),
)
